# Generated by Django 3.2 on 2021-06-03 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=20, verbose_name='Restaurant Name')),
                ('desc', models.TextField(default=' ', max_length=50, verbose_name='Description')),
                ('food', models.TextField(default=' ', max_length=30, verbose_name='Food')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.TextField(blank=True, default='', null=True)),
                ('open', models.DateTimeField(blank=True, null=True)),
                ('close', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='$')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('desc', models.TextField(max_length=200, verbose_name='Description')),
                ('restaurant', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Delivery.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productsInside', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.product')),
            ],
        ),
    ]
