# Generated by Django 3.2 on 2021-06-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='close',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='desc',
            field=models.TextField(blank=True, max_length=50, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='food',
            field=models.TextField(blank=True, max_length=30, verbose_name='Food'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.TextField(max_length=20, verbose_name='Restaurant Name'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='open',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
