# Generated by Django 3.2.5 on 2021-07-19 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0003_restaurant_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
